Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-16.10"
  config.vm.box_check_update = false
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
  end

  
  config.vm.define "example-host" do |this|
    this.vm.hostname = "example-host"
    this.vm.network "private_network", ip: "10.8.42.10"
  end
  

  config.ssh.username   = "vagrant"
  config.ssh.password   = "vagrant"
  config.ssh.insert_key = false
end
